#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
language: java
jdk:
- openjdk8
dist: bionic
notifications:
  email:
    recipients:
    - dev@dattack.com
    on_success: always
    on_failure: always
cache:
  directories:
  - "~/.m2/repository"
env:
  global:
  - secure: Znjr3UgHzLNE3fLK97+JAxkEzrA4L6CViLjOes6sFP4vpxNqQ3MqtLyVMwxjuVNZq1OT96+hDbc6ZLSeCJFQdywWmA93XCXNMcSbCvmZrY2pN9M2rQCYZlxdgccptgQToEUUVepGqaLme7G4OvGUKMkR0iFIbssjcZIRi3FgqH7AxiWToXjls3C5YaoVxlZgLpSAz10Q4DX3iA9YVVMBJ36R78CFTaNf7ytTri+zkp4XC8SMCIy9sbbVy3k8Rd/V4ieBnzMd1Mip7jxdtyYiD4PRGq2kvMt+d1+3iOGOLv4HDqwtHhbtj4bIk7FayUujnvsniMwpkbRkyV9hoQ+Xsv/BbTUhESXtVBnJKSNsP7qvdzNjxcmSkJdngMeFUL0lFCOlYDZOjKA0/C2+EeAyfvThJ7x5s6X1D79/esa2DVPi9hYrsBiUDemywWbWuiHreNSRRHdVebCpDwnVK6ZliU63uW0SjSfig1sCETLXmQIMJl8parXQT0Frr5c/0CqX3/62McEZeiEgyK8EUfOE5tOMND1SHvyGKrkGYp2W/ShEiwTRd49x4gWavhIuMbp/k4McQdvzSbAmjpi7WIeiFlHjXt37TSUH8R5xSUcQ9PzJUBIdQ6JeKpFDOLBLqVtyNCIb1Z1r4BnQxFaMMLy48AQEZtC+14o+5gVn54hyEyQ=
  - secure: FpSdYiekJl616ox/Q3bKJDADBPiWVyYc3RZAxlUCdqM8yDlaJyI32JFrZdlpdYiD7ILTAmedgEW/hYrtgfJHyfMC5NsV966nF05ApzPmMXXc1rX0jWBvvyS/ReD6NlUe1/xW/D3bAFauhHnLTC9drpcsWC7f3hQ8QPiLGpVFKxwwvi+LP0AogDRLS/DgXy9tJZ4M73XQ8JQOKVKnmT5IzpGvAYNYLAXX+ubv4VgmhXW6v3mCjQ92d9zNU31Zi3L89z69MBI3GjFoCdBowk5opJ/m8iw0ZabCuYXuhv3tCqLPIm5PPhWE/BZUFu6rNnRtLXhH81KjPZfnLkrBsBzXXrre/RkuWghi4eH4KrKd/faePcbVRRQB3T3GZlq6YfZ2MC4fVy0QfT+NhzP4vizy2nlHImop44WD+Rmc4CddrFqkyRcvjnYtKWBe8gqrLOyD1NqQBHaJBDd+cImVfAyiEXKvyW5aHFZ80VhSiA4m3NIwiRLU9nt5cFBRm9VMV4BXPlSO71csg653tFY4uW6DZbquDQxahJ0/7iqOCLrIo5r4AvUA+fJJcK3GFnR54wa+NrOi0AZW9tml2DyYD7gW+kWOEvQCZsw4meaVnb5VwmFe9WOV0JxjFrngBE/z4SrUdNcqic4HZ1dOEvftVBRGIhqwnugyzbIiE7cdO2yxYcg=
  - secure: TitzrDLDtB+oYvQdHSvDSA0dVNF9A/eN7tYQ639EHsHw4y4GqdXF1hwvnzXwz5UGa5ueO02iLei7PGBDMrJxC1kcrlvMcZ9DJO5jIqxvV3zW2xe3DIdYJ2v6lySNW85dCU1lLedhphqLDsI8i2v47ZZ3GVjNZ3Ui+cFjKPjeQbP9D5ximW53/yVm0Y9vyJJ84DxW7XnsSH+MnJhqaupTOtuynf/Lz9vGPgDkDXICgLlEYXE5+sQF1DNSK1UtzYuaU646vZ68uahX1kTczJTt5aTHUnJ8vP2Zg7BhejOck0oy/1YCLFXKIfQY1+RdaLXBpMCjJiRDKGPv0rmruhJ3ba2D54tWbOwlfEEjmnOtYdB8zx1m7UlXPUGjGc/mVgTdaRgHIGYXD9qN53hAy+P1wBvHkQ6W9sUm5hAPl0hhNYqBdB4KgLyXJM1kac4Pbnu8LKd2teE+mQuG5dqkxiXvZZBEvToBNJsBXMszjqBHhIiWmbwFLQntBrscfY+5Zf7c9jEj+l4sRWdj/MNiZn8Rw6FdPgyxUpgR+Owr7mHW/dO0aQ+mJNkm4tHS6LGaS/lUyOwXR/MeMBHvM6ZzdF/28fTAMIY379BVYgBXqbT6n8hjeJGPhddt3eGN9x7YAfLqEaXgOkpjVeXHMZWwdeve0vedseNt1G8SwLoUTLEs8SI=
  - secure: icOaqI3bSeuDDjTWxv8jqmEKM4XBUIdvfRtGGPu0/DUDiXF6kdj5xcjL6h4Gp4Y7aKxbgMXwpZIduVLiXPa7oUeMLU2C6dzwFIVF47LUUE8LWMsuxJ388MZ/xlYp2T0C97zztDtwyzhOfF72eTj4zijieVgj2c7cmHcW2gF5dCKW7yOGoLXHbiU0VEgYPo8Ft+gxdgA64bn9Zn0KHVJXvC4mCfdV3N6MjfDoS9hcnE4pK4soAob5A4P9/W1ilQLAydNxxtjwQg1Z9ULvgT7ZuloGWHRFeqpjE6afPx7GdPIgY14inU72yC77E3Rw6GC6P3v71t4U+Cvh8p96WOdVsIgvp0mdius8PyJxhrGhgAJZfUtN8s+qQM0gCFZEoFG6JlCUXYMhXJwCc4y9fAMRktWZ+IcPFarnvCQL1U5kB5T1ijP68G0MV5P23h7cMWS6q37Yrq4O2ZE6KlU1UOi/+UWBnvrFaPCcelV0dHgVitTjizfg4n6OH8MzTZFGRuFFshURbcZyJ3V1FyB6NFW/ylOEwmqVoip1ttSheY88RDi1YLO5t1rtqTYhftbigbvcLQ/Oc+pxL2oVr9Z8VRyFykBTrrCxNoGeuNkU8sJslcAfmr8nbhbr0JltsIlnTXTWCKPA/OZWlRSHeOgWRjlsfJyGqgYlCZ6ff8XqHO6mHRo=
install: mvn -P !build-extras install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn -P !build-extras test -B
before_install:
- openssl aes-256-cbc -K $encrypted_711e5bbf5b76_key -iv $encrypted_711e5bbf5b76_iv
  -in .travis/codesigning.asc.enc -out .travis/codesigning.asc -d
- gpg --batch --fast-import .travis/codesigning.asc
deploy:
  skip_cleanup: true
  provider: script
  script: mvn -P sign,build-extras -s .travis/settings.xml deploy -DskipTests
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^(master|develop)$"

